services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway  
   
  redis:
    image: redis
    container_name: redis
    restart : always

    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart : always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest 

  gateway:
    build: ./backend/gateway
    container_name: gateway
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/gateway/.env
    volumes:
      - ./backend/gateway:/app
      - /app/node_modules
    depends_on:
      - auth-service  
      - agent-service

  auth-service:  
    build: ./backend/services/auth-service
    container_name: auth-service
    restart: always
    ports:
      - "4001:4001"
    env_file:
      - ./backend/services/auth-service/.env
    volumes:
      - ./backend/services/auth-service:/app
      - /app/node_modules
    depends_on:

      - redis

  agent-service:  
    build: ./backend/services/agent-service
    container_name: agent-service
    restart: always
    ports:
      - "4002:4002"
    env_file:
      - ./backend/services/agent-service/.env
    volumes:
      - ./backend/services/agent-service:/app
      - /app/node_modules
    depends_on:

      - redis    
  
  worker-service:  
    build: ./backend/services/worker-service
    container_name: worker-service
    restart: always
    ports:
      - "4003:4003"
    env_file:
      - ./backend/services/worker-service/.env
    volumes:
      - ./backend/services/worker-service:/app
      - /app/node_modules
    depends_on:
      - redis
    
  # frontend: 
  #   build: ./frontend
  #   container_name: frontend
  #   restart: always
  #   ports:
  #     - "1000:3000"
  #   environment:
  #     - WATCHPACK_POLLING=true
  #     - CHOKIDAR_USEPOLLING=true
  #   env_file:
  #     - ./frontend/.env
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #     - /app/.next
    
